use phf::phf_map;
use std::fmt;
use std::str::FromStr;

use crate::error::EDGARError;

#[derive(Debug, PartialEq, Eq, Hash, Clone, Copy)]
#[allow(missing_docs)]
pub enum FilingTypeOption {
    _1A,
    _1E,
    _1K,
    _1N,
    _1SA,
    _1U,
    _1Z,
    _10,
    _10D,
    _10K,
    _10M,
    _10Q,
    _11K,
    _12B25,
    _13F,
    _13H,
    _144,
    _15,
    _15F,
    _17H,
    _18,
    _18K,
    _19B4,
    _19B4E,
    _19B7,
    _2E,
    _20F,
    _24F2,
    _25,
    _3,
    _4,
    _40F,
    _5,
    _6K,
    _7M,
    _8A,
    _8K,
    _8M,
    _9M,
    ABS,
    ABS15G,
    ABSEE,
    ADV,
    ADVE,
    ADVH,
    ADVNR,
    ADVW,
    ATS,
    ATSN,
    ATSR,
    BD,
    BDN,
    BDW,
    C,
    CA1,
    CB,
    CFPORTAL,
    CRS,
    CUSTODY,
    D,
    F1,
    F10,
    F3,
    F4,
    F6,
    F7,
    F8,
    F80,
    FN,
    FX,
    ID,
    MA,
    MAI,
    MANR,
    MAW,
    MSD,
    MSDW,
    N14,
    N17D1,
    N17F1,
    N17F2,
    N18F1,
    N1A,
    N2,
    N23C3,
    N27D1,
    N3,
    N4,
    N5,
    N54A,
    N54C,
    N6,
    N6EI1,
    N6F,
    N8A,
    N8B2,
    N8B4,
    N8F,
    NCEN,
    NCR,
    NCSR,
    NMFP,
    NPORT,
    NPX,
    NQ,
    NRN,
    NRSRO,
    PF,
    PILOT,
    R31,
    S1,
    S11,
    S20,
    S3,
    S4,
    S6,
    S8,
    SBSE,
    SBSEA,
    SBSEBD,
    SBSEC,
    SBSEW,
    SCI,
    SD,
    SDR,
    SE,
    SF1,
    SF3,
    SIP,
    T1,
    T2,
    T3,
    T4,
    T6,
    TA1,
    TA2,
    TAW,
    TCR,
    TH,
    WBAPP,
    X17A19,
    X17A5,
    X17F1A,
}

// Static map for string -> enum conversion
static FILING_TYPE_MAP: phf::Map<&'static str, FilingTypeOption> = phf_map! {
        FilingTypeOption::_1 => "1".to_string(),
        FilingTypeOption::_1A => "1-A".to_string(),
        FilingTypeOption::_1E => "1-E".to_string(),
        FilingTypeOption::_1K => "1-K".to_string(),
        FilingTypeOption::_1N => "1-N".to_string(),
        FilingTypeOption::_1SA => "1-SA".to_string(),
        FilingTypeOption::_1U => "1-U".to_string(),
        FilingTypeOption::_1Z => "1-Z".to_string(),
        FilingTypeOption::_10 => "10".to_string(),
        FilingTypeOption::_10D => "10-D".to_string(),
        FilingTypeOption::_10K => "10-K".to_string(),
        FilingTypeOption::_10M => "10-M".to_string(),
        FilingTypeOption::_10Q => "10-Q".to_string(),
        FilingTypeOption::_11K => "11-K".to_string(),
        FilingTypeOption::_12B25 => "12B-25".to_string(),
        FilingTypeOption::_13F => "13F".to_string(),
        FilingTypeOption::_13H => "13H".to_string(),
        FilingTypeOption::_144 => "144".to_string(),
        FilingTypeOption::_15 => "15".to_string(),
        FilingTypeOption::_15F => "15F".to_string(),
        FilingTypeOption::_17H => "17-H".to_string(),
        FilingTypeOption::_18 => "18".to_string(),
        FilingTypeOption::_18K => "18-K".to_string(),
        FilingTypeOption::_19B4 => "19b-4".to_string(),
        FilingTypeOption::_19B4E => "19b-4(E)".to_string(),
        FilingTypeOption::_19B7 => "19b-7".to_string(),
        FilingTypeOption::_2E => "2-E".to_string(),
        FilingTypeOption::_20F => "20-F".to_string(),
        FilingTypeOption::_24F2 => "24F-2".to_string(),
        FilingTypeOption::_25 => "25".to_string(),
        FilingTypeOption::_3 => "3".to_string(),
        FilingTypeOption::_4 => "4".to_string(),
        FilingTypeOption::_40F => "40-F".to_string(),
        FilingTypeOption::_5 => "5".to_string(),
        FilingTypeOption::_6K => "6-K".to_string(),
        FilingTypeOption::_7M => "7-M".to_string(),
        FilingTypeOption::_8A => "8-A".to_string(),
        FilingTypeOption::_8K => "8-K".to_string(),
        FilingTypeOption::_8M => "8-M".to_string(),
        FilingTypeOption::_9M => "9-M".to_string(),
        FilingTypeOption::ABS => "ABS".to_string(),
        FilingTypeOption::ABS15G => "ABS-15G".to_string(),
        FilingTypeOption::ABSEE => "ABS-EE".to_string(),
        FilingTypeOption::ADV => "ADV".to_string(),
        FilingTypeOption::ADVE => "ADV-E".to_string(),
        FilingTypeOption::ADVH => "ADV-H".to_string(),
        FilingTypeOption::ADVNR => "ADV-NR".to_string(),
        FilingTypeOption::ADVW => "ADV-W".to_string(),
        FilingTypeOption::ATS => "ATS".to_string(),
        FilingTypeOption::ATSN => "ATS-N".to_string(),
        FilingTypeOption::ATSR => "ATS-R".to_string(),
        FilingTypeOption::BD => "BD".to_string(),
        FilingTypeOption::BDN => "BD-N".to_string(),
        FilingTypeOption::BDW => "BDW".to_string(),
        FilingTypeOption::C => "C".to_string(),
        FilingTypeOption::CA1 => "CA-1".to_string(),
        FilingTypeOption::CB => "CB".to_string(),
        FilingTypeOption::CFPORTAL => "CFPORTAL".to_string(),
        FilingTypeOption::CRS => "CRS".to_string(),
        FilingTypeOption::CUSTODY => "CUSTODY".to_string(),
        FilingTypeOption::D => "D".to_string(),
        FilingTypeOption::F1 => "F-1".to_string(),
        FilingTypeOption::F10 => "F-10".to_string(),
        FilingTypeOption::F3 => "F-3".to_string(),
        FilingTypeOption::F4 => "F-4".to_string(),
        FilingTypeOption::F6 => "F-6".to_string(),
        FilingTypeOption::F7 => "F-7".to_string(),
        FilingTypeOption::F8 => "F-8".to_string(),
        FilingTypeOption::F80 => "F-80".to_string(),
        FilingTypeOption::FN => "F-N".to_string(),
        FilingTypeOption::FX => "F-X".to_string(),
        FilingTypeOption::ID => "ID".to_string(),
        FilingTypeOption::MA => "MA".to_string(),
        FilingTypeOption::MAI => "MA-I".to_string(),
        FilingTypeOption::MANR => "MA-NR".to_string(),
        FilingTypeOption::MAW => "MA-W".to_string(),
        FilingTypeOption::MSD => "MSD".to_string(),
        FilingTypeOption::MSDW => "MSDW".to_string(),
        FilingTypeOption::N14 => "N-14".to_string(),
        FilingTypeOption::N17D1 => "N-17D-1".to_string(),
        FilingTypeOption::N17F1 => "N-17F-1".to_string(),
        FilingTypeOption::N17F2 => "N-17F-2".to_string(),
        FilingTypeOption::N18F1 => "N-18F-1".to_string(),
        FilingTypeOption::N1A => "N-1A".to_string(),
        FilingTypeOption::N2 => "N-2".to_string(),
        FilingTypeOption::N23C3 => "N-23C-3".to_string(),
        FilingTypeOption::N27D1 => "N-27D-1".to_string(),
        FilingTypeOption::N3 => "N-3".to_string(),
        FilingTypeOption::N4 => "N-4".to_string(),
        FilingTypeOption::N5 => "N-5".to_string(),
        FilingTypeOption::N54A => "N-54A".to_string(),
        FilingTypeOption::N54C => "N-54C".to_string(),
        FilingTypeOption::N6 => "N-6".to_string(),
        FilingTypeOption::N6EI1 => "N-6EI-1".to_string(),
        FilingTypeOption::N6F => "N-6F".to_string(),
        FilingTypeOption::N8A => "N-8A".to_string(),
        FilingTypeOption::N8B2 => "N-8B-2".to_string(),
        FilingTypeOption::N8B4 => "N-8B-4".to_string(),
        FilingTypeOption::N8F => "N-8F".to_string(),
        FilingTypeOption::NCEN => "N-CEN".to_string(),
        FilingTypeOption::NCR => "N-CR".to_string(),
        FilingTypeOption::NCSR => "N-CSR".to_string(),
        FilingTypeOption::NMFP => "N-MFP".to_string(),
        FilingTypeOption::NPORT => "N-PORT".to_string(),
        FilingTypeOption::NPX => "N-PX".to_string(),
        FilingTypeOption::NQ => "N-Q".to_string(),
        FilingTypeOption::NRN => "N-RN".to_string(),
        FilingTypeOption::NRSRO => "NRSRO".to_string(),
        FilingTypeOption::PF => "PF".to_string(),
        FilingTypeOption::PILOT => "PILOT".to_string(),
        FilingTypeOption::R31 => "R31".to_string(),
        FilingTypeOption::S1 => "S-1".to_string(),
        FilingTypeOption::S11 => "S-11".to_string(),
        FilingTypeOption::S20 => "S-20".to_string(),
        FilingTypeOption::S3 => "S-3".to_string(),
        FilingTypeOption::S4 => "S-4".to_string(),
        FilingTypeOption::S6 => "S-6".to_string(),
        FilingTypeOption::S8 => "S-8".to_string(),
        FilingTypeOption::SBSE => "SBSE".to_string(),
        FilingTypeOption::SBSEA => "SBSE-A".to_string(),
        FilingTypeOption::SBSEBD => "SBSE-BD".to_string(),
        FilingTypeOption::SBSEC => "SBSE-C".to_string(),
        FilingTypeOption::SBSEW => "SBSE-W".to_string(),
        FilingTypeOption::SCI => "SCI".to_string(),
        FilingTypeOption::SD => "SD".to_string(),
        FilingTypeOption::SDR => "SDR".to_string(),
        FilingTypeOption::SE => "SE".to_string(),
        FilingTypeOption::SF1 => "SF-1".to_string(),
        FilingTypeOption::SF3 => "SF-3".to_string(),
        FilingTypeOption::SIP => "SIP".to_string(),
        FilingTypeOption::T1 => "T-1".to_string(),
        FilingTypeOption::T2 => "T-2".to_string(),
        FilingTypeOption::T3 => "T-3".to_string(),
        FilingTypeOption::T4 => "T-4".to_string(),
        FilingTypeOption::T6 => "T-6".to_string(),
        FilingTypeOption::TA1 => "TA-1".to_string(),
        FilingTypeOption::TA2 => "TA-2".to_string(),
        FilingTypeOption::TAW => "TA-W".to_string(),
        FilingTypeOption::TCR => "TCR".to_string(),
        FilingTypeOption::TH => "TH".to_string(),
        FilingTypeOption::WBAPP => "WB-APP".to_string(),
        FilingTypeOption::X17A19 => "X-17A-19".to_string(),
        FilingTypeOption::X17A5 => "X-17A-5".to_string(),
        FilingTypeOption::X17F1A => "X-17F-1A".to_string(),
};

impl FromStr for FilingTypeOption {
    type Err = EDGARError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        FILING_TYPE_MAP
            .get(&s.to_uppercase() as &str)
            .copied()
            .ok_or(EDGARError::FilingTypeNotFound)
    }
}

impl fmt::Display for FilingTypeOption {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let value = match self {
            FilingTypeOption::_1 => "1".to_string(),
            FilingTypeOption::_1A => "1-A".to_string(),
            FilingTypeOption::_1E => "1-E".to_string(),
            FilingTypeOption::_1K => "1-K".to_string(),
            FilingTypeOption::_1N => "1-N".to_string(),
            FilingTypeOption::_1SA => "1-SA".to_string(),
            FilingTypeOption::_1U => "1-U".to_string(),
            FilingTypeOption::_1Z => "1-Z".to_string(),
            FilingTypeOption::_10 => "10".to_string(),
            FilingTypeOption::_10D => "10-D".to_string(),
            FilingTypeOption::_10K => "10-K".to_string(),
            FilingTypeOption::_10M => "10-M".to_string(),
            FilingTypeOption::_10Q => "10-Q".to_string(),
            FilingTypeOption::_11K => "11-K".to_string(),
            FilingTypeOption::_12B25 => "12B-25".to_string(),
            FilingTypeOption::_13F => "13F".to_string(),
            FilingTypeOption::_13H => "13H".to_string(),
            FilingTypeOption::_144 => "144".to_string(),
            FilingTypeOption::_15 => "15".to_string(),
            FilingTypeOption::_15F => "15F".to_string(),
            FilingTypeOption::_17H => "17-H".to_string(),
            FilingTypeOption::_18 => "18".to_string(),
            FilingTypeOption::_18K => "18-K".to_string(),
            FilingTypeOption::_19B4 => "19b-4".to_string(),
            FilingTypeOption::_19B4E => "19b-4(E)".to_string(),
            FilingTypeOption::_19B7 => "19b-7".to_string(),
            FilingTypeOption::_2E => "2-E".to_string(),
            FilingTypeOption::_20F => "20-F".to_string(),
            FilingTypeOption::_24F2 => "24F-2".to_string(),
            FilingTypeOption::_25 => "25".to_string(),
            FilingTypeOption::_3 => "3".to_string(),
            FilingTypeOption::_4 => "4".to_string(),
            FilingTypeOption::_40F => "40-F".to_string(),
            FilingTypeOption::_5 => "5".to_string(),
            FilingTypeOption::_6K => "6-K".to_string(),
            FilingTypeOption::_7M => "7-M".to_string(),
            FilingTypeOption::_8A => "8-A".to_string(),
            FilingTypeOption::_8K => "8-K".to_string(),
            FilingTypeOption::_8M => "8-M".to_string(),
            FilingTypeOption::_9M => "9-M".to_string(),
            FilingTypeOption::ABS => "ABS".to_string(),
            FilingTypeOption::ABS15G => "ABS-15G".to_string(),
            FilingTypeOption::ABSEE => "ABS-EE".to_string(),
            FilingTypeOption::ADV => "ADV".to_string(),
            FilingTypeOption::ADVE => "ADV-E".to_string(),
            FilingTypeOption::ADVH => "ADV-H".to_string(),
            FilingTypeOption::ADVNR => "ADV-NR".to_string(),
            FilingTypeOption::ADVW => "ADV-W".to_string(),
            FilingTypeOption::ATS => "ATS".to_string(),
            FilingTypeOption::ATSN => "ATS-N".to_string(),
            FilingTypeOption::ATSR => "ATS-R".to_string(),
            FilingTypeOption::BD => "BD".to_string(),
            FilingTypeOption::BDN => "BD-N".to_string(),
            FilingTypeOption::BDW => "BDW".to_string(),
            FilingTypeOption::C => "C".to_string(),
            FilingTypeOption::CA1 => "CA-1".to_string(),
            FilingTypeOption::CB => "CB".to_string(),
            FilingTypeOption::CFPORTAL => "CFPORTAL".to_string(),
            FilingTypeOption::CRS => "CRS".to_string(),
            FilingTypeOption::CUSTODY => "CUSTODY".to_string(),
            FilingTypeOption::D => "D".to_string(),
            FilingTypeOption::F1 => "F-1".to_string(),
            FilingTypeOption::F10 => "F-10".to_string(),
            FilingTypeOption::F3 => "F-3".to_string(),
            FilingTypeOption::F4 => "F-4".to_string(),
            FilingTypeOption::F6 => "F-6".to_string(),
            FilingTypeOption::F7 => "F-7".to_string(),
            FilingTypeOption::F8 => "F-8".to_string(),
            FilingTypeOption::F80 => "F-80".to_string(),
            FilingTypeOption::FN => "F-N".to_string(),
            FilingTypeOption::FX => "F-X".to_string(),
            FilingTypeOption::ID => "ID".to_string(),
            FilingTypeOption::MA => "MA".to_string(),
            FilingTypeOption::MAI => "MA-I".to_string(),
            FilingTypeOption::MANR => "MA-NR".to_string(),
            FilingTypeOption::MAW => "MA-W".to_string(),
            FilingTypeOption::MSD => "MSD".to_string(),
            FilingTypeOption::MSDW => "MSDW".to_string(),
            FilingTypeOption::N14 => "N-14".to_string(),
            FilingTypeOption::N17D1 => "N-17D-1".to_string(),
            FilingTypeOption::N17F1 => "N-17F-1".to_string(),
            FilingTypeOption::N17F2 => "N-17F-2".to_string(),
            FilingTypeOption::N18F1 => "N-18F-1".to_string(),
            FilingTypeOption::N1A => "N-1A".to_string(),
            FilingTypeOption::N2 => "N-2".to_string(),
            FilingTypeOption::N23C3 => "N-23C-3".to_string(),
            FilingTypeOption::N27D1 => "N-27D-1".to_string(),
            FilingTypeOption::N3 => "N-3".to_string(),
            FilingTypeOption::N4 => "N-4".to_string(),
            FilingTypeOption::N5 => "N-5".to_string(),
            FilingTypeOption::N54A => "N-54A".to_string(),
            FilingTypeOption::N54C => "N-54C".to_string(),
            FilingTypeOption::N6 => "N-6".to_string(),
            FilingTypeOption::N6EI1 => "N-6EI-1".to_string(),
            FilingTypeOption::N6F => "N-6F".to_string(),
            FilingTypeOption::N8A => "N-8A".to_string(),
            FilingTypeOption::N8B2 => "N-8B-2".to_string(),
            FilingTypeOption::N8B4 => "N-8B-4".to_string(),
            FilingTypeOption::N8F => "N-8F".to_string(),
            FilingTypeOption::NCEN => "N-CEN".to_string(),
            FilingTypeOption::NCR => "N-CR".to_string(),
            FilingTypeOption::NCSR => "N-CSR".to_string(),
            FilingTypeOption::NMFP => "N-MFP".to_string(),
            FilingTypeOption::NPORT => "N-PORT".to_string(),
            FilingTypeOption::NPX => "N-PX".to_string(),
            FilingTypeOption::NQ => "N-Q".to_string(),
            FilingTypeOption::NRN => "N-RN".to_string(),
            FilingTypeOption::NRSRO => "NRSRO".to_string(),
            FilingTypeOption::PF => "PF".to_string(),
            FilingTypeOption::PILOT => "PILOT".to_string(),
            FilingTypeOption::R31 => "R31".to_string(),
            FilingTypeOption::S1 => "S-1".to_string(),
            FilingTypeOption::S11 => "S-11".to_string(),
            FilingTypeOption::S20 => "S-20".to_string(),
            FilingTypeOption::S3 => "S-3".to_string(),
            FilingTypeOption::S4 => "S-4".to_string(),
            FilingTypeOption::S6 => "S-6".to_string(),
            FilingTypeOption::S8 => "S-8".to_string(),
            FilingTypeOption::SBSE => "SBSE".to_string(),
            FilingTypeOption::SBSEA => "SBSE-A".to_string(),
            FilingTypeOption::SBSEBD => "SBSE-BD".to_string(),
            FilingTypeOption::SBSEC => "SBSE-C".to_string(),
            FilingTypeOption::SBSEW => "SBSE-W".to_string(),
            FilingTypeOption::SCI => "SCI".to_string(),
            FilingTypeOption::SD => "SD".to_string(),
            FilingTypeOption::SDR => "SDR".to_string(),
            FilingTypeOption::SE => "SE".to_string(),
            FilingTypeOption::SF1 => "SF-1".to_string(),
            FilingTypeOption::SF3 => "SF-3".to_string(),
            FilingTypeOption::SIP => "SIP".to_string(),
            FilingTypeOption::T1 => "T-1".to_string(),
            FilingTypeOption::T2 => "T-2".to_string(),
            FilingTypeOption::T3 => "T-3".to_string(),
            FilingTypeOption::T4 => "T-4".to_string(),
            FilingTypeOption::T6 => "T-6".to_string(),
            FilingTypeOption::TA1 => "TA-1".to_string(),
            FilingTypeOption::TA2 => "TA-2".to_string(),
            FilingTypeOption::TAW => "TA-W".to_string(),
            FilingTypeOption::TCR => "TCR".to_string(),
            FilingTypeOption::TH => "TH".to_string(),
            FilingTypeOption::WBAPP => "WB-APP".to_string(),
            FilingTypeOption::X17A19 => "X-17A-19".to_string(),
            FilingTypeOption::X17A5 => "X-17A-5".to_string(),
            FilingTypeOption::X17F1A => "X-17F-1A".to_string(),
        };
        write!(f, "{}", value)
    }
}

// Re-exported helpers for your API
pub fn filing_from_str(s: &str) -> Result<FilingTypeOption, EDGARError> {
    FilingTypeOption::from_str(s)
}

pub fn to_string(filing_type: FilingTypeOption) -> String {
    filing_type.to_string()
}

pub fn validate_filing_type_string(s: &str) -> Result<String, EDGARError> {
    let ft = filing_from_str(s)?;
    Ok(ft.to_string())
}
